### ISSUE TITLE
Update Maven Build

### ISSUE THREAD

**Issue by phreed** [CategoricalData/fql#101]
mvn package
...
72 errors similar to the following.
...
[ERROR] /fql/src/catdata/aql/exp/EdsExp.java:[142,24] invalid method declaration; return type required
[ERROR] /fql/src/catdata/aql/exp/EdsExp.java:[152,24] invalid method declaration; return type required
[ERROR] /fql/src/catdata/aql/exp/EdsExp.java:[270,24] class, interface, or enum expected
[ERROR] /fql/src/catdata/aql/exp/EdsExp.java:[271,31] class, interface, or enum expected
[ERROR] /fql/src/catdata/aql/exp/EdsExp.java:[272,25] class, interface, or enum expected
[ERROR] /fql/src/catdata/aql/exp/EdsExp.java:[273,25] class, interface, or enum expected
...

**Comment by wisnesky** [comment]
My local copy (which has exactly the tip) compiles fine from scratch in eclipse.  Could this be a maven thing?  Can you be more specific about the error?  My EdsExp.java is only 100 lines long - maybe you are seeing an old version of it?

**Comment by wisnesky** [comment]
Speaking of Maven, there’s a dependency on apache commons lang now too.

**Comment by phreed** [comment]
[You are right somehow the version I had of the EdsExp.java was wrong. ]

You mean ... http://commons.apache.org/proper/commons-lang/ ?
Hence ...
```
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.7</version>
 </dependency>
```

I did a check on the library versions specified in the maven pom file.
```
The following dependencies in Dependencies have newer versions:
  com.fifesoft:autocomplete .............................. r239 -> 2.6.1
  com.h2database:h2 ................................. 1.4.193 -> 1.4.196
  com.opencsv:opencsv ...................................... 3.10 -> 4.1
  net.sf.jung:jung-algorithms ........................... 2.0.1 -> 2.1.1
  net.sf.jung:jung-api .................................. 2.0.1 -> 2.1.1
  net.sf.jung:jung-graph-impl ........................... 2.0.1 -> 2.1.1
  net.sf.jung:jung-visualization ........................ 2.0.1 -> 2.1.1
  org.apache.commons:commons-csv ............................ 1.4 -> 1.5
  org.glassfish:javax.json .............................. 1.0.4 -> 1.1.2
```
Which versions are correct?

**Comment by wisnesky** [comment]
That’s correct, commons-lang.  I came for the CompareToBuilder but stayed for the EqualsBuilder and HashCodeBuilder.

I have not been upgrading the AQL dependencies; I just use the jars in /lib.  If you can verify that the new versions of those libraries work, that would be great.  Even better would be if you can update /lib too.

**Comment by phreed** [comment]
ok, I will look into that.

**Comment by phreed** [comment]
I asked maven to identify all of the dependencies and copy those libraries.
Here is a list of libraries that maven thinks should be included but were not in `lib`.
```
	lib/ST4-4.0.8.jar
	lib/antlr-runtime-3.5.2.jar
	lib/antlr4-4.7.jar
	lib/commons-beanutils-1.9.3.jar
	lib/commons-collections-3.2.2.jar
	lib/commons-logging-1.2.jar
	lib/commons-text-1.1.jar
	lib/guava-19.0.jar
	lib/icu4j-58.2.jar
	lib/org.abego.treelayout.core-1.0.3.jar
	lib/org.apache.servicemix.bundles.cglib-3.2.4_1.jar
```
Should these be included in `lib` as well?

**Comment by wisnesky** [comment]
When I build in Eclipse, I just use the jar files in the /lib.  Since everything builds without jars for the libraries you mention in the lib, then either those libraries aren’t needed, the jar files in /lib contain the libraries you mention embedded in their own jars, or the libraries you mention are new dependencies for new versions of the libraries AQL does require.  Either way I’m inclined not to add anything to the /lib.

**Comment by phreed** [comment]
ok, I did not add them. The pull request should be fine. I will close this issue.
