### ISSUE TITLE
Generated SQL issues : problem with unnest?

### ISSUE THREAD

**Issue by phreed** [CategoricalData/fql#115]
When looking at the sql produced for composed queries I get things like this...

```
(0) create view outputQ as   
(1) select 
(2)     concat(concat('("(ce,"(v,2)")"=', concat(convert("(ce,"(v,2)")".id, varchar), ')')), 
(3)            concat('(v46=', concat(convert(v46.id, varchar), ')'))) as id, 
(4)     "(ce,"(v,2)")".cot_type as cot_type
(5) from 
(6)     inputcot_detail as "(ce,"(v,2)")", 
(7)     inputcot_action as v46
(8) where 
(9)       v46.has_cot_detail = "(ce,"(v,2)")".id 
(a)   and "(ce,"(v,2)")".cot_type = 'a-n-A-C-F-m' 
(b)   and v46.id = "(ce,"(v,2)")".has_cot_action
```

The issues with this result are:
lines (2,4,6,9,a,b) : the alias does not seem to be correctly formed [too many quote marks].
```
  "(ce,"(v,2)")"
  "(ce,(v,2))"
```
line (6,7) : where is the "input" prefix coming from?
line (0) : where is the "output" prefix coming from?

The following is more what I expected.

```
(0) create view Q as   
(1) select 
(2)     concat(concat('("(ce,(v,2))"=', concat(convert("(ce,(v,2))".id, varchar), ')')), 
(3)            concat('(v46=', concat(convert(v46.id, varchar), ')'))) as id, 
(4)     "(ce,(v,2))".cot_type as cot_type
(5) from 
(6)     cot_detail as "(ce,(v,2))", 
(7)     cot_action as v46
(8) where 
(9)       v46.has_cot_detail = "(ce,(v,2))".id 
(a)   and "(ce,(v,2))".cot_type = 'a-n-A-C-F-m' 
(b)   and v46.id = "(ce,(v,2))".has_cot_action
```

The table naming issue appears in simple queries as well.
I am guessing this is to avoid a name collision?

```
(0) create view outputQ as   
(1) select 
(2)     concat('(ce=', concat(convert(ce.id, varchar), ')')) as id, 
(3)     ce.cot_type as cot_type
(4) from 
(5)     inputcot_event as ce
(6) where 
(7)     ce.cot_type = 'a-n-A-C-F-m'

```
line (5) : where is the "input" prefix coming from?
line (0) : where is the "output" prefix coming from?

**Comment by phreed** [comment]
There seems to be a bug that only shows up on the first run.
The attached file illustrates the problem.

14:42:23.042 [worker-1] ERROR aql.wrap - cannot generate sql for query #error {
 :cause already contains v0

v0:cot_detail
 :via
 [{:type java.lang.RuntimeException
   :message already contains v0

v0:cot_detail
   :at [catdata.Ctx put Ctx.java 146]}]
 :trace
 [[catdata.Ctx put Ctx.java 146]
  [catdata.aql.Query elimNested Query.java 190]
  [catdata.aql.Query unfoldNestedApplications Query.java 126]
  [catdata.aql.Query unnest Query.java 74]
  [sun.reflect.NativeMethodAccessorImpl invoke0 NativeMethodAccessorImpl.java -2]
  [sun.reflect.NativeMethodAccessorImpl invoke NativeMethodAccessorImpl.java 62]
  [sun.reflect.DelegatingMethodAccessorImpl invoke DelegatingMethodAccessorImpl.java 43]
  [java.lang.reflect.Method invoke Method.java 498]
  [clojure.lang.Reflector invokeMatchingMethod Reflector.java 93]
  [clojure.lang.Reflector invokeNoArgInstanceMember Reflector.java 313]

[brass_data.txt](https://github.com/CategoricalData/fql/files/1738120/brass_data.txt)

**Comment by wisnesky** [comment]
this should be fixed now

**Comment by phreed** [comment]
6e65a74907901ef65ac959666096f913f1b3c8e3 fixed 'v0' error.
eff93217d1350d21a1f08070794ff5a289ebbdd9 removes 'input' and 'output' prefix
93cf675f219021b82fcba6e761e28e9261821b70 generate sql alias names without quotes [some provenance lost [that is fine]]
