### ISSUE TITLE
Emacs support

### ISSUE THREAD

**Issue by epost** [CategoricalData/fql#119]
@wisnesky Hi, I made https://github.com/epost/aql-mode. It currently provides very basic AQL syntax highlighting in Emacs. There's some stuff fairly straightforward stuff that could be added to enable interactive notebooks using org-mode, where you'd get syntax highlighting and code evaluation, which in turn could be exported to HTML, Latex, OpenDocument Text, Beamer or Reveal slides, or what have you. Would this be a good candidate for putting under its own repo, say CategoricalData/aql-mode?

**Comment by wisnesky** [comment]
I'm happy to host it here, or I'm sure state box would be happy to do so as well.  Either way, I'm cleaning out these old issues so if you need to me to do anything, let me know.
