### ISSUE TITLE
High-DPI file chooser test

### ISSUE THREAD

**Issue by wisnesky** [CategoricalData/fql#12]
Hi Peter,

As of Dec 17, I switched to a native file chooser widget for the IDE.  Can you switch back to 4K and tell me if you have any high-DPI text clarity problems with open/save? 

While you're at it, can you double check that switching to the java look and feel fixed the high-DPI text size problems as well?  I think it did but I don't actually remember testing it at 4K while you were here.

**Comment by peterygates** [comment]
Will do. Having problems with my computer. Lost my mouse enroute and since
my keyboard and mouse use the same wireless usb connection it seems if I
try to use an old mouse it is incompatable with the keyboard. heading to
the store for a replacement.

**Comment by peterygates** [comment]
Never mind, the usual solution fixed the problem, reboot. Back in business.

**Comment by peterygates** [comment]
Now the text on menus and buttons are so small as to be unreadable. On the
plus side it seems the scaling between the 4k monitor and the HD monitor
work perfectly. That is, equally unreadable on both. If I open the Windows
magnifier everything looks great, but that application is unusable for
normal work as far as I am concerned.

**Comment by wisnesky** [comment]
Can you elaborate by assigning one of {legible, too small} to each of the four (resolution, test) pairs below:

 - (1080p, main IDE window)
 - (1080p, file choosers in open/save)
 - (4K, main IDE window)
 - (4K, file choosers in open/save)

Don’t forget to quit the IDE between each test - it is unlikely the IDE will work correctly if the resolution is changed while it is running.

**Comment by peterygates** [comment]
I fiddled around with some of the advanced display settings to overcome the
problem. For example I can enlarge the font for menu items etc. using the
advanced display settings, which works great for other apps but not for the
FQL IDE.

**Comment by peterygates** [comment]
Doesn't seem to make any difference whether I reset the resolution to 1080
or 4k. I did notice that the file chooser looks like other apps with the
exception of the icons to the left of the "Look in:" dropdown just below
the Open title bar. These icons seem to be at the same scale (barely
visible) as the IDE. Note: the Title bar is fine on the IDE.

- (1080p, main IDE window) Same as 4k
- (1080p, file choosers in open/save) Same as 4k
- (4K, main IDE window) Unreadable
- (4K, file choosers in open/save) Ok (except icons mentioned above)

**Comment by wisnesky** [comment]
I don’t understand - when you left here, I thought the new “skin” made the IDE usable on your laptop at at least one resolution.  Did something change?  Or was the IDE never actually useable when you were here?

**Comment by peterygates** [comment]
I downloaded the latest build. Did you make a change?

**Comment by peterygates** [comment]
I had it running when I opened my laptop and when I downloaded the latest
version and restarted everything was microscopic.

**Comment by wisnesky** [comment]
I made two changes:

 - the file chooser is now “native”
 - on windows, the UI defaults to the “java” skin

I was expecting the main window to look exactly the same as when you left, and for the file chooser to look like a native file chooser.

**Comment by wisnesky** [comment]
Try deleting the cdide.ser file on your desktop, maybe that will help.

When you click file->about, does it say “Packaged on December 17 or after?”

**Comment by wisnesky** [comment]
Also make sure when you download fql.jar you ‘save as’ to your desktop.

**Comment by peterygates** [comment]
Well I had to use the magnifier to read the about dialog and yes it does
say: "Packaged: December 17, 2016 or later".

I deleted the cdide.ser file and no change. Yes I did save as to my desktop
otherwise I would not have the most recent version of the About menu.

**Comment by peterygates** [comment]
By the way I figured out that if I dock the magnifier I can get by,
although I am not happy.

**Comment by wisnesky** [comment]
I don’t understand what could have changed.  Can you verify the IDE is using this look and feel:

https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/nimbus.html

Can you go through the look and feels in the options menu and see if any of them make the IDE useable?

Do you have an old jar somewhere?  If so can you test to see if the old jar is really tiny?

**Comment by peterygates** [comment]
I tried them all and each one works perfect except for they are all equally
too small. I will hunt for an old jar and try it if I find one, but I think
I have been overwriting each time I download.

**Comment by peterygates** [comment]
Can't find any old downloads. I was able to fix the problem with mySQL
though. The following works fine:

instance J = import_jdbc
"com.mysql.jdbc.Driver"
"jdbc:mysql://localhost:3306/employees?user=root&password=HappyFunctor"
 : S2 {
Employee -> "SELECT concat('e', id) FROM Employee"
Department -> "SELECT concat('d', id) FROM Department"
  department -> "SELECT concat('e', id), concat('d', department_id) FROM
Employee"
first -> "SELECT concat('e', id), first_name FROM Employee"
  last -> "SELECT concat('e', id), last_name FROM Employee"
  name -> "SELECT concat('d', id), name FROM Department"
}

I will close the GitHub issue.

**Comment by peterygates** [comment]
Taking a break.

**Comment by peterygates** [comment]
Would it be helpful to open a hangout and share my desktop? I am going to
start the grill in an hour or so and will be off line for the rest of the
evening.

**Comment by wisnesky** [comment]
Peter, can you remind me what we concluded about this issue?  I think we decided that high-DPI support is just a matter of waiting for java 9, but until then using the metal look and feel as default on windows was the best way to avoid high-DPI issues (and we did this).  Are there any other remaining glaring high-DPI related issues?

**Comment by peterygates** [comment]
No, as far as I am concerned we can close it.
