### ISSUE TITLE
Create or update project planning

### ISSUE THREAD

**Issue by epost** [CategoricalData/fql#124]
I'm creating a new issue here to keep #121 on topic. Here's what @phreed suggested over there https://github.com/CategoricalData/fql/issues/121#issuecomment-379844388:

> Would it be good to add a work plan somewhere?
> The wiki maybe?
...
> https://github.com/orgs/CategoricalData/projects

FWIW, this project does have [milestones](https://github.com/CategoricalData/fql/milestones) defined. They could do with some updating though. Fred, do you think milestones would suffice for the sort of planning you're thinking of?

**Comment by phreed** [comment]
Milestones would be a good start.
I would like to see the fql project split up a bit.
Milestones only apply to single projects.
The separation I would like to see:
- desktop application
- grammars and parsers
- examples
- microservices
- engine/solvers as a library
 
A while back Ryan and I discussed what should be included in a beta release.
Ryan also created a wiki http://catinf.com/wiki/Main_Page

Ryan made some issues for most (all?) of them.
I have some commitments to do a few of them myself.
Here is the list we discussed at the time [Ryan did not agree with all of these].

 - fast sigma/colimit operations based on the chase 
 - new java 9 style platform-specific executables, i.e. jlinked so no JDK install needed
 - a build process that makes the compile time accessible to the IDE, so the IDE can display a version number
 - the AQL grammar expressed in an extension of ANTLR4
    - the ANTLR parser
    - documentation generated from the ANTLR extended grammar instead of the latex.
 - a test suite
 - elements of AQL presented as libraries
 - an family of AQL servers suitable for use as micro-services, ZMQ & REST
 - example projects in various domains [how do we split built-in from external?]
 - query composition for all types of SQL functionality [they need only be isomorphic]
   - an adapter for SQL can complete the transformation.
 - migrate updates, i.e. handle the "functorial view-update problem"
 - schema and schema mapping inference
 - support for composition of partial queries [done]

**Comment by epost** [comment]
@phreed Great stuff!

Re some of the functionality you mention, I'm not sufficiently knowledgeable yet to have much of an opinion. However, I agree that modularisation is absolutely crucial. (As an experiment, I tried deleting all GUI and non-AQL stuff from my local project source tree last week, but what I was left with seemed to have quite a few problematic interdependencies, so it seems that modularisation would require a bit more thought and likely a fair bit of refactoring. Still, every step in the right direction would be great. I hope to have a closer look soon.) 

It seems that the microservice thing would be relatively easy to achieve in the form of external projects as soon as things have been modularised (i.e. librarified).

What, or which extension, do you mean by 'the AQL grammar expressed in an extension of ANTLR4'? The AQL parser is already defined in (vanilla) ANTLR4, right?

Are there any issues you mention here that aren't proper issues yet?

**Comment by phreed** [comment]
Actually, the Antlr4 parser is not actually the active parser, so that is the second thing to do.
The first thing is to bring the grammar up-to-date, it has migrated a bit.
Next I want to embellish the grammar with additional information that can be used to produce a reference guide. The Antlr grammar does not allow for such 'literate programming' so I will extend Antlr a bit. Then we want the grammar to be used to generate code for editors similar to [Xtext](https://www.eclipse.org/Xtext/).

**Comment by wisnesky** [comment]
The AQL parser is actually based on parser combinators:

https://github.com/jparsec/jparsec <https://github.com/jparsec/jparsec>

A proper ANTLR parser would enable a lot of functionality.

I agree with Fred’s list.  Do you two need me to be doing anything specific to help you?  My focus is on the faster sigmas and colimit operations right now.

**Comment by wisnesky** [comment]
These plans are dated enough to start a new thread if needed.
