### ISSUE TITLE
Add a chat facility to the repo / organisation?

### ISSUE THREAD

**Issue by epost** [CategoricalData/fql#126]
It may be a good idea to have a project-related chat, e.g. on Slack, or possibly on Gitter. Neither issues nor the maling list seem like quite the right place for some of the project-related discussion. I'm willing to make this happen. 

Concretely, I propose to add a `categoricaldata` Slack with for example an `aql` channel.

Thoughts, @phreed @wisnesky @peterygates?

**Comment by phreed** [comment]
That sounds good to me.

**Comment by wisnesky** [comment]
Works for me.  I’ve never actually used Slack or its alternatives.

**Comment by epost** [comment]
Oh drat, I think I misread your comments because i was viewing them in my email instead of on github. It seems like you *don't* think it's particularly useful. I do agree Slack has its downsides, and the expiration is an important one.  Hmm. :/

**Comment by phreed** [comment]
Slack is fine. There are just so many placing where discussions are happening.
 https://groups.google.com/forum/#!forum/categoricaldata is probably more suitable for end users than developers.

**Comment by epost** [comment]
Yeah, I agree on both points.
