### ISSUE TITLE
Annotate ANTLR4 grammar so that documentation and tools can be generated from it

### ISSUE THREAD

**Issue by epost** [CategoricalData/fql#129]
phreed: 

> I want to embellish the grammar with additional information that can be used to produce a reference guide. The Antlr grammar does not allow for such 'literate programming' so I will extend Antlr a bit. Then we want the grammar to be used to generate code for editors similar to Xtext.

Depends on #128.

**Comment by wisnesky** [comment]
I did something similar creating a co-visitor class and implementing it with an inverted typing relation.  The documentation is now generated from that, so I guess I'll close this.
