### ISSUE TITLE
AQL query return '*'

### ISSUE THREAD

**Issue by phreed** [CategoricalData/fql#130]
A feature of sql queries is the ability to use '*' to indicate all of the columns associated with a particular table.

```
set schema 'sS';

select f.*, b.*
from Foo as f, Bar as b;
```

```
query q1 = simple : sS {
from	f : Foo, b : Bar
return  * -> f.* , * -> b.*
}
```

**Comment by phreed** [comment]
This targets the new ANTLR based parser.

**Comment by wisnesky** [comment]
see newest commit
