### ISSUE TITLE
Inconsistent Generic Type Signature

### ISSUE THREAD

**Issue by phreed** [CategoricalData/fql#131]
As I was working through the compiler warnings I ran across some bugs related to inconsistent generic type signatures.
In some cases the types are of the form <Ty, Sym, En, Fk,... > and in other cases they are of the form <Ty, En, Sym, Fk,... >
In general this is not a problem except in a few cases where wildcards are used.
I think the best way to handle this is to be consistent in the generic type signatures.
I prefer <Ty, Sym, En, Fk,... > as that order seems move from more to less significant.

**Comment by wisnesky** [comment]
Can you tell me where these are so I can fix them?  I try to be consistent but accidents happen.

**Comment by phreed** [comment]
Sorry I took so long to get back on this I wanted to get that pull request in.
I do not remember where the problem is now.
I found it when I was working through the compiler warnings.
I will close this issue now and open a new one the next time I go through the warnings.
