### ISSUE TITLE
Positive testing / verification for AQL programs

### ISSUE THREAD

**Issue by wisnesky** [CategoricalData/fql#30]
Positive testing / verification for AQL programs is to demonstrate that AQL programs succeed when they should succeed.

Ways in which AQL programs are Positive tested / verified:

 - There are no built-in limits to the time and memory an AQL program can use
 - Soon, users can generate random instances in AQL which can be used to test

TODO 1: besides random instances, are there other ways to help AQL programmers easily construct sample data?

TODO 2: static analysis for AQL programs.  In other words, how to prove that an AQL program has a certain property.  For example, how would you prove that a particular instance will be consistent?  Or have no nulls?  In the pushout design pattern, we proved that the result must be consistent if the inputs are consistent and the pushout schema is used (I think?).  The idea of this todo is to be able to go to someone who has an AQL program and guarantee them some useful property about it, given some assumptions about its inputs.

**Comment by dspivak** [comment]
1.A. They could upload it from a spreadsheet.
1.B. You could have a wizard or something, where: they add a row, it shows them the result (the spread of labeled nulls throughout the database), and then they have the option of equating things, quitting, or repeating.

2.A. If there are no equations, it should be consistent. 
2.B. If it comes from a spreadsheet it should be consistent and has no labeled nulls.
2.C. If they enter the data "old FQL style", i.e. as a saturated instance, it should be consistent and have no labeled nulls.
