### ISSUE TITLE
Graph tab bug in Exe GUI

### ISSUE THREAD

**Issue by peterygates** [CategoricalData/fql#33]
When I moved a node (entity) over to the edge of the Graph viewer for a schema the slider at the bottom properly indicated that there was something off screen to the left but when I attempted to move the slider to the left it snapped back to its former position. I tried to resize the window but was unable to get the node back into the viewer. I closed and reopened the viewer and was able to reproduce the problem. I am running the NimbusLookAndFeel.

**Comment by wisnesky** [comment]
We’re at the mercy of the JUNG graph toolkit here: they implement their own custom scroll pane, and it’s not something I can easily modify.

But, there is a workaround: you can zoom the graph in and out by scrolling up and down with the mouse wheel.

I can probably do two things:

 - arrange for + and - keystrokes to zoom the graph in and out.
 - add + and - buttons to the graph to indicate zoom.

but that leads to two questions:

 - would we want to put a label somewhere to indicate that +/- can be used?
 - adding +/- buttons would take up an entire “row” or “column” in the graph UI - is adding buttons worth the loss of space?

**Comment by peterygates** [comment]
Ryan,

Whatever you do make it the easiest possible thing. Seriously consider
doing nothing at all. Notice I assigned a low priority to the bug report.
The reason I brought it up is that if you choose to use that library in the
MVP you should be aware of its limitations. If you do not choose to use
that library in the MVP I don't think it is worth the time to spend on work
arounds.

Just to follow up on this thread. I think we need a more flexible tool for
rendering diagrams. We have discussed this already. If this means moving to
some totally different toolkit than my advice is don't spend any time
futzing with JUNG.

**Comment by wisnesky** [comment]
Yeah, we’re going to have to buy a graph-drawing GUI library for the MVP.  I’ve looked into a couple already but haven’t started a serious comparison of the various options yet.
