### ISSUE TITLE
open with

### ISSUE THREAD

**Issue by dspivak** [CategoricalData/fql#48]
When I get an AQL file, I'd like to be able to run my Mac's "open with" feature, pointing it to FQL. But being a .jar file, I guess my mac doesn't recognize that it can run files. 

Can this be changed?

**Comment by wisnesky** [comment]
I looked into this and concluded the situation is hopeless until we acquire more resources: to do this  requires building custom wrappers for mac / windows that are aware of things like "open with", I don't know how to do that, and it looks to be very hard, or at least, very specialized.  There is no oracle-sanctioned way to get this behavior out of the box.  So I am marking this as "wont fix" and we can revisit later.  In the interim, on mac the "FQL droplet" sort of works; I tried a similar hack on windows but couldn't make it work.

**Comment by wisnesky** [comment]
Two requests:

- It does not search for the right file name; my fql is named fql-17, and it doesn't find it. I edited the script in the script editor, changing the expected file name in two spots to fql-17, but that didn't work. So I changed the file name to fql.jar and it worked.

- If there is already an FQL open, it opens a second one.
