### ISSUE TITLE
mapping translate: give me options

### ISSUE THREAD

**Issue by dspivak** [CategoricalData/fql#50]
In the viewer, when I scroll to a mapping, there is a tab called "Translate", which asks for input.

But I have no idea at this stage what I can input. How about offering a list of examples to which I can point and click?

**Comment by wisnesky** [comment]
I changed the text labels on the translate tab to be more clear.  But, I doubt anyone will use this pane; mostly, I kept it around to help me with debugging  and I don't really use it anymore.  For that reason, I'm considering removing it altogether - and unless you object, I won't beef it up.  What it does is take as input a term-in-context t in a schema C, and prints out subst(F, t), where F : C -> D is the schema mapping being viewed.

**Comment by dspivak** [comment]
Ok, although I can imagine power users using it. Peter, thoughts?

**Comment by wisnesky** [comment]
I'm not actually sure who can read comments when no one is "assigned" (usually I assign people who should participate).  The person who opened it always gets notified on new comments, and so do I, but I'm not sure about anyone else.  So this will be a test to see who is watching...

**Comment by dspivak** [comment]
i'm watching, but i don't think the test question is very clear.
