### ISSUE TITLE
mappings: allow foreign key syntax for attributes

### ISSUE THREAD

**Issue by dspivak** [CategoricalData/fql#62]
When writing mappings, the foreign key mappings are easy to write (f->f) whereas the attribute mappings are harder (f->lambda x.f(x)), or at least very different. 

I understand why we have to do this: because we can have n-ary function symbols in attributes. But sometimes I'm just doing something 1-ary. It'd be nice to have the option of just writing in the simpler foreign-key style when 1-ary.

**Comment by wisnesky** [comment]
done
