### ISSUE TITLE
ramdom instance feature

### ISSUE THREAD

**Issue by dspivak** [CategoricalData/fql#65]
Given a schema S, I want a way to form a random instance. This would help a lot with testing.

As pragma, I want to specify how many generating rows per table, and number of equations per table in the saturation.

instance I = random : S {
  pragma 
    generators_per_table = 3
    equations_per_table = 1

Given the spec, the machine first adds all the generators and then saturates. Then it forms equations, possibly duplicates, among the rows in the saturation.

**Comment by wisnesky** [comment]
This looks as follows (copied from built-in Employees example):

instance IRandom = random : SJava {
	generators
		Employee -> 10
		Department -> 2
}

creates an instance presentation with 10,2 generators.  Then for each generator e:s and fk/att f : s -> t, it adds equation f(e) = y, where y:t is a randomly selected generator (or no equation if t has no generators).

This leads to "dense" instance presentations but hopefully it will be enough for scalability testing.

The random number seed can be set as e.g. options random_seed = 2.

**Comment by dspivak** [comment]
nice!
