### ISSUE TITLE
help with syntax??

### ISSUE THREAD

**Issue by dspivak** [CategoricalData/fql#66]
I want to write observation_equations in my schema. I wonder what the syntax for them is. 

What to do? I look for a help menu; nothing. I look for built-in examples; after looking through five or six, none seem to have observation_equations. I highlight observation_equations, the context-sensitive help doesn't seem to help.

**Comment by wisnesky** [comment]
There is now a Help button on the main IDE that displays a help text file that can contain whatever we want.  For now it just points to the manual (which has detailed syntax) and tutorial.
