### ISSUE TITLE
Visual cues/stereotype for the new outline feature

### ISSUE THREAD

**Issue by jeechung2001** [CategoricalData/fql#76]
The newly added outline (right pane) feature is great for quickly navigating a file. It would be even better if the outline had additional visual cues to stereotype the labels. For example, as a reader of the code, I'd find it useful to quickly determine which labels are type sides, which are schemas, which are queries, etc.

**Comment by wisnesky** [comment]
There is already an option to turn on labels - typeside, schema, etc - in the IDE’s option’s menu.  These labels are off by default.

**Comment by jeechung2001** [comment]
Got it. I see it. It helps. I was thinking of visual cues such as color or icons, but for now the text labels are good for the purpose.

**Comment by jeechung2001** [comment]
Thanks, Ryan. Love the enhanced navigation capability!
