### ISSUE TITLE
documentation on imports

### ISSUE THREAD

**Issue by dspivak** [CategoricalData/fql#82]
I'd like documentation, say in the AQL manual, about what to expect from the **imports** command. It's unclear what it actually does. For example, if I write

transform h : J -> J {
 imports id J 
}

Should I assume that it imports the identity map on generators? Or should I assume that it imports the identity map on saturations?! Those are quite different, and for some reason I find myself wanting the former.

**Comment by wisnesky** [comment]
I added a new section in the manual called Imports and made it clear that the imports have to be names, and that the semantics is textual inclusion.  There is category theory - institution theory - that gives a precise semantics to textual inclusion of theories and theory morphisms, but basically, AQL will in fact do the right thing on your example and h and id J will denote the same thing.
