### ISSUE TITLE
Errata in example: resources/examples/aql/Tutorial TSP.aql

### ISSUE THREAD

**Issue by phreed** [CategoricalData/fql#87]
The line is ...
A directed graph `C` is a pair of functions source: `C_0` -> `C_1` and target: `C_0` -> `C_1`.
...I think this should be...
A directed graph `C` is a pair of functions source: `C_1` -> `C_0` and target: `C_1` -> `C_0`.
The functions take edges (C_1) to nodes (C_0), correct?

**Comment by wisnesky** [comment]
I've assigned this to Peter, because he wrote the tutorial.

**Comment by wisnesky** [comment]
It looks like this has been fixed in the latest Tutorial TSP.aql, so I am closing this issue.
