### ISSUE TITLE
Provide toAqlLiteral method

### ISSUE THREAD

**Issue by phreed** [CategoricalData/fql#95]
I have a need to serialize a composed query.
I am thinking something like a `toString()` method would be appropriate.
i.e. `toAqlLiteral()`
The need is to be able to produce a 
serialization that approximates what might have been 
written by hand as a query literal in AQL.
It would be useful to be able to export the
literal representation of any object.
The purpose is to synchronize with other durable storage [mostly graph databases].

I understand that there is a lot more structure associated with
the query and I would not mind having access to that as well
but it is not immediately necessary.

The triggering of these could be made in a pragma?
Where the output file where they would be written could be specified.

**Comment by wisnesky** [comment]
I made Query's toString method print the inside of a literal.

As for triggering toString in a pragma, I should expose the AQL environment being constructed to the javascript engine, so that pragmas could invoke arbitrary functions on the instances, schemas, in the AQL program.  Let me think about how to do that.

**Comment by wisnesky** [comment]
Ok, you can now refer to the AqlEnvironment under construction from the exec_js pragma:

pragma p = exec_js {
	"javax.swing.JOptionPane.showMessageDialog(null, aql_env.toString())"
}

**Comment by phreed** [comment]
Great, I will give it a try.

**Comment by phreed** [comment]
cb22973bb544f7498d206fa0f431dcc4a99e65b0 expose the AQL environment the exec_js pragma
6781f9e58f46a3aef710c89f27b8c931451bdc51 Query's toString method print the inside of a literal
